/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.io.Serializable;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.table.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
/**
 *
 * @author 전현빈
 */
public class Register extends JFrame implements Serializable{



   
   public Object[][] tempTest;
   public String[] tempTableList = { "상품 id", "상품이름", "가격", "상품종류", "상품설명", "재고" };
   public Function myFt;
   public DefaultTableModel model = new DefaultTableModel(tempTest, tempTableList);
   private JTable jTable1 = new JTable(model);

   void deserial() {
      try {
         FileInputStream fis = new FileInputStream(new File("product.dat"));
         ObjectInputStream ois = new ObjectInputStream(fis);
         model = (DefaultTableModel) ois.readObject();
         ois.close();
         fis.close();
      } catch (IOException ioe) {
         ioe.printStackTrace();
         return;
      } catch (ClassNotFoundException c) {
         System.out.println("파일을 찾지 못했습니다.");
         c.printStackTrace();
         return;
      }
   }
   
   void serial(){
      try {
         FileOutputStream fos = new FileOutputStream(new File("product.dat"));
         ObjectOutputStream oos = new ObjectOutputStream(fos);
         oos.writeObject(model);
         oos.close();
         fos.close();
      } catch (IOException ioe) {
         ioe.printStackTrace();
      }
   }

   public Register() {
      getContentPane().setFont(new Font("-윤고딕330", Font.PLAIN, 12));
      tempTest = new String[20][6];
      tempTableList = new String[] { "상품 id", "상품이름", "가격", "상품종류", "상품설명", "재고" };
      myFt = new Function();
      deserial();

      jTable1 = new JTable(model);
      // tempTest = myFt.catalog();

      setResizable(false);
        initComponents();
        goToCenter();
     // makeList();
    }
   public void mouseClicked(java.awt.event.MouseEvent e){
      if(e.getButton() == 1){
         int row = jTable1.getSelectedRow();
      }
   }
     public void goToCenter()
    {
        Dimension frameSize = this.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        this.setLocation((screenSize.width - frameSize.width)/2, 
                (screenSize.height - frameSize.height)/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

       jScrollPane2 = new javax.swing.JScrollPane();
       jList1 = new javax.swing.JList<>();
       jScrollPane1 = new javax.swing.JScrollPane();

       jLabel1 = new javax.swing.JLabel();
       jLabel1.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField1 = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel3.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField2 = new javax.swing.JTextField();
       jLabel4 = new javax.swing.JLabel();
       jLabel4.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField3 = new javax.swing.JTextField();
       jLabel5 = new javax.swing.JLabel();
       jLabel5.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField4 = new javax.swing.JTextField();
       jLabel6 = new javax.swing.JLabel();
       jLabel6.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField5 = new javax.swing.JTextField();
       jLabel7 = new javax.swing.JLabel();
       jLabel7.setFont(new Font("08서울남산체 B", Font.PLAIN, 12));
       jTextField6 = new javax.swing.JTextField();
       jButton_Back = new javax.swing.JButton();
       jButton_Back.setFont(new Font("나눔고딕", Font.PLAIN, 15));
       jButton_Delete = new javax.swing.JButton();
       jButton_Delete.setFont(new Font("나눔고딕", Font.PLAIN, 15));
       jButton_Add = new javax.swing.JButton();
       jButton_Add.setFont(new Font("나눔고딕", Font.PLAIN, 15));

       jList1.setModel(new javax.swing.AbstractListModel<String>() {
          String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

          public int getSize() {
             return strings.length;
          }

          public String getElementAt(int i) {
             return strings[i];
          }
       });
       jScrollPane2.setViewportView(jList1);

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       // jTable1.setModel(new javax.swing.table.DefaultTableModel(tempTest,
       // tempTableList
       // ) {
       // Class[] types = new Class [] {
       // java.lang.Integer.class, java.lang.Integer.class,
       // java.lang.String.class, java.lang.Integer.class,
       // java.lang.String.class, java.lang.String.class,
       // java.lang.Integer.class
       // };
       //
       // public Class getColumnClass(int columnIndex) {
       // return types [columnIndex];
       // }
       // });
       jScrollPane1.setViewportView(jTable1);

       jLabel1.setBackground(new java.awt.Color(204, 204, 204));
       jLabel1.setText("상품 id");
       jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField1ActionPerformed(evt);
          }
       });

       jLabel3.setText("상품이름");
       jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField2.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField2ActionPerformed(evt);
          }
       });

       jLabel4.setText("가격");
       jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField3.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField3ActionPerformed(evt);
          }
       });

       jLabel5.setText("상품종류");
       jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField4.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField4ActionPerformed(evt);
          }
       });

       jLabel6.setText("재고");
       jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField5.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField5ActionPerformed(evt);
          }
       });

       jLabel7.setText("상품설명");
       jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       jTextField6.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextField6ActionPerformed(evt);
          }
       });

       jButton_Back.setText("돌아가기");
       jButton_Back.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             jButton_Back_Performed(evt);
          }
       });

       jButton_Delete.setText("삭제");
       jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             
             jTable1.getSelectedRow();
             jButton_Delete_Performed(evt);
             serial();

          }
       });

       jButton_Add.setText("추가");
       jButton_Add.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
             myFt.regist(jTextField1.getText(), jTextField2.getText(), Integer.parseInt(jTextField4.getText()),
                   jTextField3.getText(), jTextField5.getText(), Integer.parseInt(jTextField6.getText()));

             jButton_Add_Performed(evt);
             serial();

          }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       layout.setHorizontalGroup(
          layout.createParallelGroup(Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                      .addComponent(jButton_Add, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.UNRELATED)
                      .addComponent(jButton_Delete, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.UNRELATED)
                      .addComponent(jButton_Back))
                   .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 398, GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                      .addGap(118)
                      .addComponent(jLabel2))
                   .addGroup(layout.createSequentialGroup()
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addGroup(layout.createParallelGroup(Alignment.LEADING)
                         .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel1)
                         .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3)
                         .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel5)
                         .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel7)
                         .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4)
                         .addComponent(jLabel6))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
          layout.createParallelGroup(Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                   .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                      .addComponent(jLabel1)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jLabel3)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jLabel4)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED)
                      .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                      .addComponent(jLabel2)
                      .addGap(189))
                   .addGroup(layout.createSequentialGroup()
                      .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
                      .addGap(18)
                      .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                         .addComponent(jButton_Delete, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton_Add, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton_Back, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                      .addContainerGap(162, Short.MAX_VALUE))))
       );
       getContentPane().setLayout(layout);

       pack();
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
    }

    private void jButton_Back_Performed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       this.setVisible(false);
       item newWin = new item();
       newWin.setVisible(true);
    }
    
    private void jButton_Delete_Performed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       
       model.removeRow(jTable1.getSelectedRow());
       jScrollPane1.setViewportView(jTable1);

       
    }

    private void jButton_Add_Performed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
       Object[] item = { jTextField1.getText(), jTextField2.getText(), jTextField4.getText(), jTextField3.getText(),
             jTextField5.getText(), jTextField6.getText() };

       model.addRow(item);
       jTable1.setModel(model);
       jScrollPane1.setViewportView(jTable1);

       

       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
       jTextField6.setText("");
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       // <editor-fold defaultstate="collapsed" desc=" Look and feel setting
       // code (optional) ">
       /*
        * If Nimbus (introduced in Java SE 6) is not available, stay with the
        * default look and feel. For details see
        * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
        * html
        */
       try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
             }
          }
       } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       // </editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
             new Register().setVisible(true);
          }
       });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;

    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration
 }