/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.Serializable;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 전현빈
 */

@SuppressWarnings("serial")
public class Pos extends JFrame implements Serializable{

	Register myRg = new Register();

	public Object[][] tempTest;
	public String[] tempTableList = {"상품이름", "가격"};

	double firstnum;
	double secondnum;
	double answer;
	String operations;
	
	int total_money = 0;
	int point_use = 0;
	int point_gain = 0;
	int my_money = 0;
	int your_money = 0;
	
	JTable original_tb = new JTable();
	DefaultTableModel cash_md = new DefaultTableModel(tempTest, tempTableList);
	JTable cash_tb = new JTable();
	
	

	/**
	 * Creates new form Pos
	 */
	public Pos() {
		setResizable(false);
		initComponents();

		goToCenter();
		jTextField_master.grabFocus();
        jTextField_master.requestFocus();
		
	}

	public void goToCenter() {
		Dimension frameSize = this.getSize();
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

		this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton_CRT = new javax.swing.JButton();
		jButton_number00 = new javax.swing.JButton();
		jButton_number0 = new javax.swing.JButton();
		jButton_number1 = new javax.swing.JButton();
		jButton_number2 = new javax.swing.JButton();
		jButton_number3 = new javax.swing.JButton();
		jButton_number6 = new javax.swing.JButton();
		jButton_number5 = new javax.swing.JButton();
		jButton_number4 = new javax.swing.JButton();
		jButton_number7 = new javax.swing.JButton();
		jButton_number8 = new javax.swing.JButton();
		jButton_number9 = new javax.swing.JButton();
		jLabel_addmoney = new javax.swing.JLabel();
		jLabel_totalmoney = new javax.swing.JLabel();
		jLabel_change = new javax.swing.JLabel();
		jLabel_reserve = new javax.swing.JLabel();
		jButton_hyungum = new javax.swing.JButton();
		jButton_pointuse = new javax.swing.JButton();
		jTextField_master = new javax.swing.JTextField(); //상품추가 옆
		jTextField_addmoney = new javax.swing.JTextField(); //금액합계 옆
		jTextField_totalmoney = new javax.swing.JTextField(); //총금액
		jTextField_change = new javax.swing.JTextField(); //거스름돈
		jTextField_reserve = new javax.swing.JTextField(); //적립금
		jButton_back = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable_basictable = new javax.swing.JTable();
		jLabel_getmoney = new javax.swing.JLabel();
		jTextField_getmoney = new javax.swing.JTextField(); //받은금액
		jLabel2 = new javax.swing.JLabel();
		jButton_pointgain = new javax.swing.JButton();
		jButton_addproduct = new javax.swing.JButton();
		jButton_end = new javax.swing.JButton();
		jButton_pointview = new javax.swing.JButton();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton_CRT.setText("CLR");
		jButton_CRT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_CRT_Performed(evt);
			}
		});

		jButton_number00.setText("00");
		jButton_number00.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number00_Performed(evt);
			}
		});

		jButton_number0.setText("0");
		jButton_number0.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number0_Performed(evt);
			}
		});

		jButton_number1.setText("1");
		jButton_number1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number1_Performed(evt);
			}
		});

		jButton_number2.setText("2");
		jButton_number2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number2_Performed(evt);
			}
		});

		jButton_number3.setText("3");
		jButton_number3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number3_Performed(evt);
			}
		});

		jButton_number6.setText("6");
		jButton_number6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number6_Performed(evt);
			}
		});

		jButton_number5.setText("5");
		jButton_number5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number5_Performed(evt);
			}
		});

		jButton_number4.setText("4");
		jButton_number4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number4_Performed(evt);
			}
		});

		jButton_number7.setText("7");
		jButton_number7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number7_Performed(evt);
			}
		});

		jButton_number8.setText("8");
		jButton_number8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number8_Performed(evt);
			}
		});

		jButton_number9.setText("9");
		jButton_number9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_number9_Performed(evt);
			}
		});
		 jButton_pointview.setText("포인트조회");
	        jButton_pointview.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton_pointview_Performed(evt);
	            }
	        });

		jLabel_addmoney.setText("금액합계");

		jLabel_totalmoney.setFont(new java.awt.Font("나눔고딕 ExtraBold", 0, 12)); // NOI18N
		jLabel_totalmoney.setText("총금액");

		jLabel_change.setFont(new java.awt.Font("나눔고딕 ExtraBold", 0, 12)); // NOI18N
		jLabel_change.setText("거스름돈");

		jLabel_reserve.setFont(new java.awt.Font("나눔고딕 ExtraBold", 0, 12)); // NOI18N
		jLabel_reserve.setText("적립금");

		jButton_hyungum.setText("현금");
		jButton_hyungum.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_hyungum_Performed(evt);
				
			}
		});

		jButton_pointuse.setText("포인트사용");
		jButton_pointuse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_pointuse_Performed(evt);
			}
		});
		
		
		jTextField_master.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_master_Performed(evt);
			}
		});
		
		jTextField_change.setText("0");
		jTextField_change.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_change_Performed(evt);
			}
		});
		
		jTextField_reserve.setText("0");
		jTextField_reserve.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_reserve_Performed(evt);
			}
		});

		jButton_back.setText("돌아가기");
		jButton_back.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_back_Performed(evt);
			}
		});

		jTable_basictable.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null } },
						new String[] { "상품이름", "가격" }));
		jScrollPane2.setViewportView(jTable_basictable);

		jLabel_getmoney.setFont(new java.awt.Font("나눔고딕 ExtraBold", 0, 12)); // NOI18N
		jLabel_getmoney.setText("받은 금액");

		jTextField_getmoney.setText("0");
		jTextField_getmoney.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_getmoney_Performed(evt);
			}
		});
		jTextField_addmoney.setText("0");
		jTextField_totalmoney.setText("0");

		jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButton_pointgain.setText("포인트적립");
		jButton_pointgain.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_pointgain_Performed(evt);
			}
		});

		jButton_addproduct.setText("상품추가");
		jButton_addproduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_addproduct_Performed(evt);
			}
		});

		jButton_end.setText("결제완료");
		jButton_end.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_end_Performed(evt);
			}
		});

		   javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jLabel_totalmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jTextField_totalmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jLabel_getmoney)
	                                .addGap(18, 18, 18)
	                                .addComponent(jTextField_getmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel_change))
	                                .addGap(18, 18, 18)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jTextField_change, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
	                                    .addComponent(jTextField_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jButton_pointgain, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_end, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_hyungum, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_pointuse, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_pointview, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(87, 87, 87)
	                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(89, 89, 89)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jButton_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_number2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_number3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jButton_number4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jButton_number7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jButton_number8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jButton_number9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addComponent(jButton_number5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jButton_number6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jButton_number0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_number00, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addGap(39, 39, 39))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jScrollPane2)
	                        .addGap(12, 12, 12))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(23, 23, 23)
	                        .addComponent(jTextField_master, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(34, 34, 34)
	                        .addComponent(jButton_addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(206, 206, 206)
	                        .addComponent(jLabel_addmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jTextField_addmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(44, Short.MAX_VALUE))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jTextField_addmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel_addmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(28, 28, 28)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jButton_number8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_number7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_number9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(18, 18, 18)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                    .addComponent(jButton_number5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jButton_number6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGap(14, 14, 14))
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                .addComponent(jButton_number4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)))
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jButton_number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jButton_number0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_number00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton_CRT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                    .addComponent(jTextField_master, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jButton_addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addGap(65, 65, 65)
	                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addComponent(jLabel_totalmoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jTextField_totalmoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                        .addGap(17, 17, 17)
	                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                            .addComponent(jLabel_getmoney)
	                                            .addComponent(jTextField_getmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                        .addGap(18, 18, 18)
	                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                            .addComponent(jLabel_change)
	                                            .addComponent(jTextField_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                        .addGap(18, 18, 18)
	                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                            .addComponent(jLabel_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jTextField_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                    .addGroup(layout.createSequentialGroup()
	                                        .addGap(28, 28, 28)
	                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(66, 66, 66)
	                                .addComponent(jButton_pointview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_pointuse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_hyungum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jButton_pointgain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                .addComponent(jButton_end, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addGap(0, 0, Short.MAX_VALUE)))
	                .addContainerGap())
	        );

	        pack();
	    }// </editor-fold>    
	private void jButton_number0_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number0.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number7_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number7.getText();
		jTextField_master.setText(entervalue);
	}

	private void jTextField_master_Performed(java.awt.event.ActionEvent evt) {
		String entervalue = jTextField_master.getText() ;
		jTextField_master.setText(entervalue);

		// TODO add your handling code here:
	}

	private void jButton_number8_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number8.getText();
		jTextField_master.setText(entervalue);

		// TODO add your handling code here:
	}

	private void jButton_number00_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number00.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number9_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number9.getText();
		jTextField_master.setText(entervalue); // TODO add your handling code here:
	}

	private void jButton_number4_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number4.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number5_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number5.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number6_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number6.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number1_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number1.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number2_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number2.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_number3_Performed(java.awt.event.ActionEvent evt) {

		String entervalue = jTextField_master.getText() + jButton_number3.getText();
		jTextField_master.setText(entervalue);
		// TODO add your handling code here:
	}

	private void jButton_CRT_Performed(java.awt.event.ActionEvent evt) {
		jTextField_master.setText("");

		// TODO add your handling code here:
	}

	private void jTextField_reserve_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField_change_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton_back_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.setVisible(false);
		demo newWin = new demo();
		newWin.setVisible(true);
	}

	private void jButton_pointview_Performed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }       
	private void jTextField_getmoney_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton_pointgain_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		point_gain = Integer.parseInt(jTextField_master.getText());
		jTextField_change.setText(Integer.parseInt(jTextField_change.getText()) - point_gain + "");
		jTextField_reserve.setText(point_gain + "");
		jTextField_master.setText("");
		
	}
	
	private void jButton_hyungum_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	
	total_money = Integer.parseInt(jTextField_addmoney.getText());
	my_money = Integer.parseInt(jTextField_master.getText().toString());
	jTextField_getmoney.setText(Integer.parseInt(jTextField_getmoney.getText()) + my_money + "");
	your_money = Integer.parseInt(jTextField_getmoney.getText()) - Integer.parseInt(jTextField_totalmoney.getText().toString()) ;
	jTextField_change.setText(your_money+"");
	
	jTextField_master.setText("");
	}

	private void jButton_addproduct_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		myRg.deserial();
		original_tb.setModel(myRg.model);
				
		for(int i = 0 ; i < myRg.model.getRowCount() ; i++){
			if( jTextField_master.getText().equals(original_tb.getValueAt(i, 0))){
				Object temp[] = { original_tb.getValueAt(i, 1), original_tb.getValueAt(i, 2)};
				cash_md.addRow(temp);
				total_money += Integer.parseInt(original_tb.getValueAt(i, 2).toString());
				jTextField_addmoney.setText(total_money+"");
				jTextField_totalmoney.setText(total_money+"");
			}
		}
		jTextField_master.setText("");
		cash_tb.setModel(cash_md);
		jScrollPane2.setViewportView(cash_tb);
	}

	private void jButton_end_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		for( int i = 0 ; i < cash_tb.getRowCount() ; i++){
			for(int j = 0; j < original_tb.getRowCount(); j++){
				if (cash_tb.getValueAt(i, 0).equals(original_tb.getValueAt(j, 1))){
					original_tb.setValueAt(Integer.parseInt(original_tb.getValueAt(j, 5).toString()) - 1, j, 5);
				}
			}
		}
		
	for(int i = 0; i < cash_md.getRowCount(); i++){
		cash_md.removeRow(i);
	}
	jScrollPane2.setViewportView(jTable_basictable);
	
	myRg.serial();
		
	jTextField_master.setText("");
	jTextField_addmoney.setText("0");
	jTextField_totalmoney.setText("0");
	jTextField_change.setText("0");
	jTextField_reserve.setText("0");
	jTextField_getmoney.setText("0");
		
	}

	private void jButton_pointuse_Performed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		point_use = Integer.parseInt(jTextField_master.getText());
		jTextField_getmoney.setText(point_use+"");
		
		jTextField_master.setText("");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Pos().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton_number7;
	private javax.swing.JButton jButton_number0;
	private javax.swing.JButton jButton_number00;
	private javax.swing.JButton jButton_CRT;
	private javax.swing.JButton jButton_hyungum;
	private javax.swing.JButton jButton_pointuse;
	private javax.swing.JButton jButton_addproduct;
	private javax.swing.JButton jButton_back;
	private javax.swing.JButton jButton_pointgain;
	private javax.swing.JButton jButton_end;
	private javax.swing.JButton jButton_number8;
	private javax.swing.JButton jButton_number9;
	private javax.swing.JButton jButton_number4;
	private javax.swing.JButton jButton_number5;
	private javax.swing.JButton jButton_number6;
	private javax.swing.JButton jButton_number1;
	private javax.swing.JButton jButton_number2;
	private javax.swing.JButton jButton_number3;
	private javax.swing.JLabel jLabel_getmoney;
	private javax.swing.JLabel jLabel_change;
	private javax.swing.JLabel jLabel_reserve;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel_addmoney;
	private javax.swing.JLabel jLabel_totalmoney;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable_basictable;
	private javax.swing.JTextField jTextField_master;
	private javax.swing.JTextField jTextField_addmoney;
	private javax.swing.JTextField jTextField_totalmoney;
	private javax.swing.JTextField jTextField_change;
	private javax.swing.JTextField jTextField_reserve;
	private javax.swing.JTextField jTextField_getmoney;
	 private javax.swing.JButton jButton_pointview;
	// End of variables declaration
}
